import "./globals.css";
import { AppContextProvider } from "./Context/ContextApi";
import { Space_Grotesk } from "next/font/google"; // ✅ Import from next/font/google
import { Toaster } from "react-hot-toast";

const grotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // pick weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${grotesk.className} antialiased`}>
        <Toaster/>
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
